### ISSUE TITLE
No screen output on macOS 12

### ISSUE THREAD

**Issue by blarrow** [AsahiLinux/m1n1#137]
I configure-boot m1n1.macho and m1n1.bin separately on macOS-12.0.1 and macOS-12.1, but no screen output of HDMI.

Then I restore macOS to 11.6 on DFU mode with ipsw file， and using m1n1.macho it works well.
I think something wrong on macOS 12+

**Comment by marcan** [comment]
Apple apparently disabled the iBoot framebuffer in 12.0 final on Mac Minis. This is completely silly and we've filed a bug, but there is no response yet.

My plan is to add iBoot-DCP support code to m1n1 to handle it ourselves, but that will take some time.

**Comment by marcan** [comment]
This is now implemented.
