### ISSUE TITLE
No HDMI output on boot

### ISSUE THREAD

**Issue by rockinrobstar** [AsahiLinux/m1n1#180]
After installing on a M1 mini, I get no HDMI output after the boot picker using a Lenovo L27m-28 monitor. Monitor works fine in macOS & Recovery/Boot picker. Install works fine with different screen (Dell UltraSharp 43).

Happy to provide any other details and conduct any testing required.

**Comment by marcan** [comment]
This is an issue with m1n1 and Apple's DCP implementation, and already reported as #159, so I'll close it as a duplicate but feel free to continue the conversation there.

There is no proper graphics driver for Linux yet, so the whole thing relies on the boot-time display. That *used* to set up by iBoot, but they dropped it in 12.0 for devices with no integrated display. It's why you can't see the iBoot screens (Apple boot logo before the progress bar starts, recovery warnings, etc.) like you can on the laptops. We had to reimplement this in m1n1, but the API Apple provides for the bootloader is kind of terrible and it ends up being flaky with some monitors.

Once there is a driver for Linux, it will work reliably like macOS does, but this is still important to improve (if possible) so the U-Boot and GRUB menus are visible...
