### ISSUE TITLE
failed to installer，macOS12.3.1,M1,curl 

### ISSUE THREAD

**Issue by zoushibo123** [AsahiLinux/m1n1#188]
xiaotaiyang@bogon asahi-installer % curl https://alx.sh | sh                                   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1049  100  1049    0     0    835      0  0:00:01  0:00:01 --:--:--   841

Bootstrapping installer:
  Checking version...
  Version: v0.3.26
  Downloading...
xiaotaiyang@bogon asahi-installer %

**Comment by marcan** [comment]
Please don't open duplicate issues.
