### ISSUE TITLE
Recovery not belong to mac

### ISSUE THREAD

**Issue by RoderickQiu** [AsahiLinux/m1n1#230]
I need to perform csrutil actions, but it shows 
![IMG_20220710_195458](https://user-images.githubusercontent.com/42290260/178144353-8163df19-058a-42d9-bd86-0be653a7e84a.jpg)
How should I do？

**Comment by marcan** [comment]
Set your default boot volume to Monterey and try again. This is expected behavior on these machines, nothing to do with Asahi (the same thing would happen with multiple macOS installs, you need to set the one you want to change boot stuff for as the default).

**Comment by RoderickQiu** [comment]
Thanks for your quick and valuable response! I'm outside now and will try it later today!

From @RoderickQiu
________________________________

**Comment by RoderickQiu** [comment]
It does work, thanks.
