### ISSUE TITLE
External Display

### ISSUE THREAD

**Issue by Chenpeel** [AsahiLinux/m1n1#306]
I used a USB-C to Display-Port wire to connect the display and my M1 Mac , but the display did not show anything.
I'm sure my wire and wiring without problem, and I have follow your introduction do I need such as install/update/upgrade....
So ,could you give me some advice.
Or they're just some problems haven not develop.
Thank you anyway.

**Comment by ydalton** [comment]
Hi,

USB-C DisplayPort Alt Mode is still work-in-process on all models.

Source: [https://github.com/AsahiLinux/docs/wiki/Feature-Support](https://github.com/AsahiLinux/docs/wiki/Feature-Support)
