### ISSUE TITLE
Redundant ldr in `cpu_reset` ?

### ISSUE THREAD

**Issue by sidkshatriya** [AsahiLinux/m1n1#316]
https://github.com/AsahiLinux/m1n1/blob/86d75d4dbaed3010e3c3529424413c92211fbe22/src/start.S#L133-L155

The purpose of `ldr x2, [sp, #-8]` line 142 does not seem clear, it could be redundant. Should it be removed ?

**Comment by sidkshatriya** [comment]
Added a proposed PR #317 that removes the ldr

**Comment by marcan** [comment]
IIRC that's just a test to make sure the stack pointer is sane and does not fault.
