### ISSUE TITLE
KDE Power Managment Issue

### ISSUE THREAD

**Issue by frankvoelker** [AsahiLinux/m1n1#380]
In KDE:

Settings -> Power Management -> Advanced Power Settings

I cannot change charge limits.

I want to stop charge at 70% and start charging once below 69%, but it always jumps back to 80% (close and re-open the view to see this).

After a system restart the "Stop charging at" resetted to 100% again.

**Comment by jgouly** [comment]
Wrong repo for this, can you close the issue?

This is a known 'issue'. The only charging limits are 80% or 100%.
You can make it persistent with https://hachyderm.io/@AsahiLinux@treehouse.systems/110560193695991160
