### ISSUE TITLE
macOS on M1 is available on GitHub Actions, so can CI builds happen there?

### ISSUE THREAD

**Issue by cclauss** [AsahiLinux/m1n1#383]
See `macos-14` at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

% `SPHardwareDataType`
```
Hardware:
    Hardware Overview:
      Model Name: Apple Virtual Machine 1
      Model Identifier: VirtualMac2,1
      Model Number: VM0001LL/A
      Chip: Apple M1 (Virtual)
      Total Number of Cores: 3
      Memory: 7 GB ...
```

Now that macOS on M1 is available on GitHub Actions, can CI builds happen there?

**Comment by jgouly** [comment]
For m1n1 cross compilation is fine, doesn't need to run on macOS/Apple Silicon.
