### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by lennylxx** [AsahiLinux/m1n1#63]
First of all, I'd like to express my gratitude and respect about what you are doing here, and I find it enjoyable to watch the work streams on YouTube even though it takes hours and I do learn a lot new stuff from them.

It occurred to me while watching you working that have you ever considered the possibility to boot Windows using m1n1, if so,  is there any plan to support Windows to make m1n1 an open sourced BootCamp?

**Comment by marcan** [comment]
Windows will never run on bare metal Apple Silicon machines without Microsoft's cooperation, as porting it requires making changes to the core Windows kernel, like it did for Linux.

It would in principle be possible to run it in a thin VM that emulates an ARM SystemReady-compliant system that can boot vanilla ARM Windows, but that's out of scope for this project; however, I heard the [pongoOS](https://github.com/checkra1n/pongoOS) guys may be interested in working on that.

Either way, actually getting a usable Windows booting on Apple Silicon with the hypervisor approach would still require developing drivers for all the hardware, which is a massive undertaking that is outside of the scope of Asahi Linux; however, the drivers we write for Linux will be licensed under permissive licenses, so others are free to use them as a base to port them to Windows.
